print "Content-Type: text/html"
print ""
print ""
print "<html>"
print "<font face="arial">"
print "<IMG SRC="http://cs.mcgill.ca/~gcormi5/206/header.png"><BR>"
print "<font size="6">Create a survey</font>"
print "<p>To create a survey, please:"
print "<ul><li>Enter a title below;"
print "<li>enter successive questions by filling up the appropriate input box and clicking ``ADD'';"
print "<li>click ``DONE'' when you are done creating this survey.</ul>"
print "You may also click ``NEW'' to start over and create a new survey.</p><hr>"
print "<form name="createSurvey" action="newSurvey.py“ method="post"><input type="submit" value="NEW"></form>"
print "<form name="endSurvey" action="endSurvey.py“ method="post"><input type="submit" value="DONE"></form>"
print "<form name="addQuestion" action="addQuestion.py“ method="post">"
print "Title of Survey: <input type="text" name="title"> <br><hr>"
print "Question: <input type="text" name="question"><br>"
print "<input type="submit" value="ADD"><hr>"
print "</form>"
print "<A HREF="./index.html">Back to welcome page</A>"
print "</font></html>"