all: testytest

testytest:
	$ g++ -std=c++11 -o testytest heapsTest.cpp heapsStudent.cpp heaps.h

gradygrade:
	$ g++ -std=c++11 -o gradygrade heapsGrading.cpp heapsStudent.cpp heaps.h

clean: 
	rm -rf *.o testytest gradygrade
